### ISSUE TITLE
I was wondering if you could create a release?

### ISSUE THREAD

**Issue by acathur** [chrisdothtml/deno-minimatch#20]
Hi, Chris! My project [dep](https://github.com/denodep/dep) is using minimatch as a dependency, I think a release tag is important for module versioning, so could you please create a release? Thanks.

**Comment by chrisdothtml** [comment]
Sure. I just made a `v3.0.4` tag (same version as the ported minimatch), so you should be able to import with:

```js
import minimatch from 'https://deno.land/x/minimatch@v3.0.4/index.js'
```

**Comment by acathur** [comment]
Thank you, bro! And also invite you to publish your deno modules to the dep registry 😁
